# Generated by Django 5.0.4 on 2024-04-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicadas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='publicadas',
            new_name='publicada',
        ),
    ]
