# Generated by Django 5.0.4 on 2024-04-05 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_rename_publicadas_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_registro',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
