# Generated by Django 5.0.4 on 2024-04-05 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_fotografia_data_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='data_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
